### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by GreatKingKeenan** [kazum1kun/ba2-batch-unpack-gui#4]
**Build 0.2.1**
-Recurrent crashing during b2a health check with variations on when it crashes. Often crashing instantly
-Recurrent crashing during b2a extraction process with variations on when it crashes. Often crashing instantly

**What I've tried**
-Adding the folder as an exclusion from Windows Defender
-Running as administrator
-Running in compatibility mode
-Running it on 2 different drives
-Redownloading
-Tested it with different folders. My main "mods" folder leads to crashes, while other folders will read fine with 0 or minimal results.

**Comment by kazum1kun** [comment]
Thank you for your report, I noticed a number of similar reports. I am investigating the issue right now.

**Comment by kazum1kun** [comment]
I pushed a fix [here](https://github.com/kazum1kun/ba2-batch-unpack-gui/releases/tag/v0.3.0), can you test and see if it fixes the issue? Thanks!

**Comment by GreatKingKeenan** [comment]
It works perfect. Thank you for the quick fix!

**Comment by kazum1kun** [comment]
That's great to hear, I guess these animations have to go for a more stable experience...
